export const AVAILABLE_CRYPTOS = [
  {
    coin: "BTC",
    name: "Bitcoin",
    icon: "https://brasilbitcoin.com.br/images/User_v3/coins/bitcoin.png",
    market: "BTCBRL",
    isFrozen: 0,
    depositAllowed: 1,
    withdrawAllowed: 1,
    makerFee: "0.20",
    takerFee: "0.50",
  },
  {
    coin: "ETH",
    name: "Ethereum",
    icon: "https://brasilbitcoin.com.br/images/User_v3/coins/ethereum.png",
    market: "ETHBRL",
    isFrozen: 0,
    depositAllowed: 1,
    withdrawAllowed: 1,
    makerFee: "0.20",
    takerFee: "0.50",
  },
  {
    coin: "USDT",
    name: "Tether",
    icon: "https://brasilbitcoin.com.br/images/User_v3/coins/tether.png",
    market: "USDTBRL",
    isFrozen: 0,
    depositAllowed: 1,
    withdrawAllowed: 1,
    makerFee: "0.20",
    takerFee: "0.50",
  },
  {
    coin: "LTC",
    name: "Litecoin",
    icon: "https://brasilbitcoin.com.br/images/User_v3/coins/litecoin.png",
    market: "LTCBRL",
    isFrozen: 0,
    depositAllowed: 1,
    withdrawAllowed: 1,
    makerFee: "0.20",
    takerFee: "0.50",
  },
  {
    coin: "XRP",
    name: "Ripple",
    icon: "https://brasilbitcoin.com.br/images/User_v3/coins/ripple.png",
    market: "XRPBRL",
    isFrozen: 0,
    depositAllowed: 1,
    withdrawAllowed: 1,
    makerFee: "0.20",
    takerFee: "0.50",
  },
  {
    coin: "BCH",
    name: "Bitcoin Cash",
    icon: "https://brasilbitcoin.com.br/images/User_v3/coins/bitcoincash.png",
    market: "BCHBRL",
    isFrozen: 0,
    depositAllowed: 1,
    withdrawAllowed: 1,
    makerFee: "0.20",
    takerFee: "0.50",
  },
  {
    coin: "DOGE",
    name: "Dogecoin",
    icon: "https://brasilbitcoin.com.br/images/User_v3/coins/dogecoin.png",
    market: "DOGEBRL",
    isFrozen: 0,
    depositAllowed: 1,
    withdrawAllowed: 1,
    makerFee: "0.20",
    takerFee: "0.50",
  },
  {
    coin: "ADA",
    name: "Cardano",
    icon: "https://brasilbitcoin.com.br/images/User_v3/coins/cardano.png",
    market: "ADABRL",
    isFrozen: 0,
    depositAllowed: 1,
    withdrawAllowed: 1,
    makerFee: "0.20",
    takerFee: "0.50",
  },
  {
    coin: "SOL",
    name: "Solana",
    icon: "https://brasilbitcoin.com.br/images/User_v3/coins/solana.png",
    market: "SOLBRL",
    isFrozen: 0,
    depositAllowed: 1,
    withdrawAllowed: 1,
    makerFee: "0.20",
    takerFee: "0.50",
  },
  {
    coin: "USDC",
    name: "USDC",
    icon: "https://brasilbitcoin.com.br/images/User_v3/coins/usdc.png",
    market: "USDCBRL",
    isFrozen: 0,
    depositAllowed: 1,
    withdrawAllowed: 1,
    makerFee: "0.20",
    takerFee: "0.50",
  },
  {
    coin: "TRX",
    name: "Tron",
    icon: "https://brasilbitcoin.com.br/images/User_v3/coins/tron.png",
    market: "TRXBRL",
    isFrozen: 0,
    depositAllowed: 1,
    withdrawAllowed: 1,
    makerFee: "0.20",
    takerFee: "0.50",
  },
  {
    coin: "BNB",
    name: "BNB",
    icon: "https://brasilbitcoin.com.br/images/User_v4/coins/bnb.png",
    market: "BNBBRL",
    isFrozen: 0,
    depositAllowed: 1,
    withdrawAllowed: 1,
    makerFee: "0.20",
    takerFee: "0.50",
  },
].filter((crypto) => crypto.depositAllowed === 1 && crypto.isFrozen === 0)

export const getPopularCryptos = () => {
  return AVAILABLE_CRYPTOS.filter((crypto) => ["BTC", "ETH", "USDT", "USDC", "BNB", "SOL"].includes(crypto.coin))
}

export const getCryptoBySymbol = (symbol: string) => {
  return AVAILABLE_CRYPTOS.find((crypto) => crypto.coin === symbol)
}
